package com.danyliuk.testjob.railwaydata.controlers;

import com.danyliuk.testjob.railwaydata.repository.CarriageTypeRepository;
import com.danyliuk.testjob.railwaydata.tables.CarriageType;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class CarriageTypeController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CarriageTypeRepository carriageTypeRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewCarriageType (@RequestParam String type
            , @RequestParam int numberSeats) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        CarriageType carriageType = new CarriageType();
        carriageType.setType(type);
        carriageType.setNumberSeats(numberSeats);
        carriageType = carriageTypeRepository.save(carriageType);
//        Iterable<CarriageType> ccc = carriageTypeRepository.findAll();
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<CarriageType> getAllCarriageTypes() {
        // This returns a JSON or XML with the users
        return carriageTypeRepository.findAll();
    }

    @GetMapping(path="/test")
    public @ResponseBody String test() {
        return new String("Privet");
    }
}

